=== daveEason/mule-demo-studio-magento-synch/src/test/resources/Customer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.example.org/customerExample" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Customer" type="cus:CustomerType" xmlns:cus="http://www.example.org/customerExample"/>
  <xs:complexType name="CustomerType">
    <xs:sequence>
      <xs:element type="xs:int" name="CustomerId"/>
      <xs:element type="xs:string" name="PersonGivenName"/>
      <xs:element type="xs:string" name="PersonFamilyName"/>
      <xs:element type="xs:string" name="AddressLine1"/>
      <xs:element type="xs:int" name="PostalCode"/>
      <xs:element type="xs:string" name="City"/>
      <xs:element type="xs:string" name="Region"/>
      <xs:element type="xs:string" name="Country"/>
      <xs:element type="xs:string" name="Email"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== daveEason/mule-demo-studio-magento-synch/src/test/resources/customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Customer xmlns:tns="http://www.example.org/customerExample" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/customerExample customer.xsd ">
  <tns:CustomerId>70894567</tns:CustomerId>
  <tns:PersonGivenName>David</tns:PersonGivenName>
  <tns:PersonFamilyName>Eason</tns:PersonFamilyName>
  <tns:AddressLine1>77 Geary St</tns:AddressLine1>
  <tns:PostalCode>94108</tns:PostalCode>
  <tns:City>San Francisco</tns:City>
  <tns:Region>CA</tns:Region>
  <tns:Country>USA</tns:Country>
  <tns:Email>david.eason@mulesoft.com</tns:Email>
</tns:Customer>
